import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/userContext";
import { Toaster } from "sonner";
import ClientProvider from "./ClientProvider";

const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Vaccine Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <UserProvider>
          <ClientProvider>{children}</ClientProvider>
        </UserProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
