import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/userContext";
import { Toaster } from "sonner";

const inter = Ubuntu({ subsets: ["latin"],weight: ["400", "500", "700"], });

export const metadata: Metadata = {
  title: "Vaccine Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          {children}
        </UserProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
